# Generated by Django 3.0.6 on 2023-10-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('volume', models.IntegerField()),
                ('top_diameter', models.IntegerField()),
                ('weight', models.IntegerField(null=True)),
                ('shape', models.CharField(max_length=200)),
            ],
        ),
    ]
