# Generated by Django 3.0.6 on 2023-10-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bottle',
        ),
    ]
