# Generated by Django 3.0.6 on 2023-10-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_bottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
