# Generated by Django 3.0.6 on 2023-10-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0004_bottle_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='refer_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
